# Add MongoDB Service
services:
  - mongo:latest

# Cache node_modules/ between jobs 
cache:
  paths:
    - node_modules/

# Define stages 
stages:
  - test

test:
  image: "node:12.13"
  stage: test
  script:
    - npm install
    - npm test
  only:
    - master
